### ISSUE TITLE
Warning spam

### ISSUE THREAD

**Issue by BinaryWaves** [JoaquimLey/faboptions#11]
Hi, I am getting a huge amount of warnings when using your library..

12-09 02:06:31.678 25296-25296/XXX W/View: requestLayout() improperly called by android.view.View{de9fb46 V.ED..... ......I. 0,70-389,186 #7f1000b7 app:id/background} during layout: running second layout pass
12-09 02:06:31.695 25296-25296/XXX W/View: requestLayout() improperly called by android.view.View{b3b91e6 V.ED..... ........ 121,-15-268,132 #7f1000ba app:id/separator} during second layout pass: posting in next frame

**Comment by JoaquimLey** [comment]
Thanks for opening this issue, I've validated and will work on fixing soon 👍

**Comment by BinaryWaves** [comment]
Thanks for the quick response and fix! I will test it out in a few minutes :) Also I really like the style, can I suggest a few features/technical requests?

**Comment by JoaquimLey** [comment]
Hi @BinaryWaves 
I'm the one who should thank you for reporting, sure just open an issue for each for easier management. 👍

**Comment by BinaryWaves** [comment]
No problem, I like your library and would like to use it in my app :) And in that case I might as well help test it and make it better along the way :)
