### ISSUE TITLE
Progress circle 

### ISSUE THREAD

**Issue by BinaryWaves** [JoaquimLey/faboptions#14]
// Feature request
[Something like this library](https://github.com/DmitryMalkovich/circular-with-floating-action-button) would be awesome for the center button, just be sure to increase the side margin on the center button by the new extra few dp.

Edit:
Or alternatively something like the center button being able to display an animated drawable or something. [A lot of potentially cool use cases](https://codepen.io/collection/HtAne/17/)

**Comment by JoaquimLey** [comment]
Thanks for the suggestion @BinaryWaves, this change would require a lot of effort, I can see this could be interesting for some applications, I'll take it into consideration.

**Comment by JoaquimLey** [comment]
I'm closing this since it would be almost impossible for me to have the time to code with API14.
