### ISSUE TITLE
Adjustable menu item margin

### ISSUE THREAD

**Issue by BinaryWaves** [JoaquimLey/faboptions#15]
// Feature request
The sub-items when clicking the center button can feel a bit cramped. It would be nice to optionally set the horizontal margin between fab menu items, the most convenient way would be through the xml entry. I think the vertical is fine, the horizontal spread is just the hickup >.<

**Comment by JoaquimLey** [comment]
Thanks for your suggestion @BinaryWaves, this goes against the original concept, if this gets enough +1's I could expose an API for that but maybe you could suggest a different default spacing.

Have you had any difficulties on selecting your button?

**Comment by BinaryWaves** [comment]
I haven't had difficulties but I have like skeleton fingers haha. I can see where people with larger fingers might have trouble selecting a menu item and accidentally touching another. possibly just 2dp of margin on both sides of a menu item would be a good default.

**Comment by JoaquimLey** [comment]
Hello @BinaryWaves thanks once again for your suggestion. This is the concept based spacing but if this gets enough +1's I might put it on the roadmap. 😎

**Comment by JoaquimLey** [comment]
Closing since there was no development.
