### ISSUE TITLE
Programmatically Set menu item color

### ISSUE THREAD

**Issue by BinaryWaves** [JoaquimLey/faboptions#16]
// Feature request

Use Case: I would like to implement an up/down vote system and it would be nice to have the up/down icons able to have their colors changed indicated the user has upvoted or downvoted the current item.

**Comment by JoaquimLey** [comment]
I believe this change could be done in a somewhat easy way, I would suggest you to contribute with a PR, this is a very specific use-case but if you require it and if you can submit a PR and both you and the rest of the community would benefit from your work 😀.

**Comment by JoaquimLey** [comment]
This will be available on the next release ;)
