### ISSUE TITLE
Menu items are shown if menu not opened

### ISSUE THREAD

**Issue by zboing** [JoaquimLey/faboptions#17]
If the user selects the line below to be used in the activity, he will notice that the menu items are shown although the menu is closed (those are not appearing if the menu is added inside the xml)
`fabOptions.setButtonsMenu(this, R.menu.menu_faboptions);`
https://postimg.org/image/8x7ycjl07/

**Comment by JoaquimLey** [comment]
Thanks for reporting @zboing.
I'll check it later today.

**Comment by idiotjr** [comment]
I'm also facing this bug.
Additionally, even when the menu icons are hidden, click on that menu item is working.
Can you please try to fix it soon. I love this library and want to use it in my app, but can't use it with this bug persisting.

Thanks for the wonderful library!

**Comment by JoaquimLey** [comment]
@idiotjr I'm currently traveling so it's been quite hard for me to get to it.
I'll be back home Sunday and hopefully, I'll have the time to finally close this issue, thanks for the kind words and patience.

**Comment by idiotjr** [comment]
@JoaquimLey Thank you. Looking forward to Sunday ☜(⌒▽⌒)☞

**Comment by JoaquimLey** [comment]
Fixed, available on next release.

**Comment by idiotjr** [comment]
thnx

**Comment by idiotjr** [comment]
don't mean to annoy you, but being a noob, i'd like to know if u have already updated it? if so how do i update dependency or will be updated automatically?
-thnx for your time

**Comment by JoaquimLey** [comment]
Hey no problem! You better of asking then dwelling, I haven't released the new version, you should expect this bug fixed on version 1.1.0 ;)

**Comment by idiotjr** [comment]
thnx. fingers crossed for the next update
