### ISSUE TITLE
Slight vertical offset of X

### ISSUE THREAD

**Issue by Gericop** [JoaquimLey/FabOptions#2]
The X symbol has a slight vertical offset downwards meaning it's not centered.

**Comment by JoaquimLey** [comment]
Hello @Gericop thanks for reporting, can you please give me a SS of this issue? Where do you find the offset?

**Comment by Gericop** [comment]
![faboptions_bug_cut](https://cloud.githubusercontent.com/assets/5181621/20643961/0752a1d2-b427-11e6-9ece-d87c84436ebb.png)

The green lines mark the top and bottom of the layout, and blue is the center line. As you can see the X's middlepoint is below the blue line.

**Comment by JoaquimLey** [comment]
Hi thanks for taking the time, I'll get to it tomorrow 👍.

**Comment by JoaquimLey** [comment]
Fixed on version 1.0.1

@Gericop thanks for reporting.
