### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by enricocid** [JoaquimLey/faboptions#20]
fabOptions.setButtonsMenu requires context. It must be changed to (I can't send You pull request)::

fabOptions.setButtonsMenu(**yourActivity.this**, R.menu.your_fab_buttons);

**Comment by JoaquimLey** [comment]
Thanks for reporting, this will be correct in the next release (It should be available soon), thanks!

**Comment by enricocid** [comment]
No problem:)
