### ISSUE TITLE
Menu item is clickable even when it hidden

### ISSUE THREAD

**Issue by idiotjr** [JoaquimLey/faboptions#25]
Hi. I've addressed this issue earlier and still haven't got a fix.
Clicking on the respective positions of menus, triggers onlick even if the menu is hidden.
Please fix this.

**Comment by idiotjr** [comment]
Okay thank you. sorry for the repost

**Comment by JoaquimLey** [comment]
No problem @idiotjr its fixed now, version 1.1.2 👍
