### ISSUE TITLE
[request] Small Fab

### ISSUE THREAD

**Issue by PawelPleskaczynski** [JoaquimLey/faboptions#32]
Hello, would it be possible for you to add an option to make the Fab small? I'd like it to be as small as high is the bar with buttons :)

**Comment by JoaquimLey** [comment]
Hi @PawelPleskaczynski Thanks for the suggestion, you can actually archive this yourself, just put the height or extend the class and set your own size :)

**Comment by PawelPleskaczynski** [comment]
Thank you :)

**Comment by JoaquimLey** [comment]
@PawelPleskaczynski but were you able to archive what you wanted?

**Comment by PawelPleskaczynski** [comment]
I haven't tried it yet

**Comment by JoaquimLey** [comment]
@PawelPleskaczynski but were you able to archive what you wanted?

**Comment by JoaquimLey** [comment]
Ok I'm closing this issue, you're always welcome to leave feedback here once you do, if you can't I'll try to help you out and reopen this issue 👍
