### ISSUE TITLE
Incorrect display after replacing fragment

### ISSUE THREAD

**Issue by J-Jamet** [JoaquimLey/faboptions#36]
Hello, 
There is a display error when the fabOptions is rebuilt into a new fragment, let me explain :
- Everything is fine when it is in the first display of the fragment.
![capture d ecran de 2017-07-07 10-47-51](https://user-images.githubusercontent.com/19224038/27950684-883a9554-6302-11e7-8adf-2568ec7116ca.png)
- But there is a problem displaying the icons when I replace by the same fragment :
 `DetailsBuddyFragment details = new DetailsBuddyFragment();
getSupportFragmentManager().beginTransaction().replace(R.id.fragment_details_buddy, details, TAG_DETAILS_FRAGMENT).commit();`
![capture d ecran de 2017-07-07 10-56-24](https://user-images.githubusercontent.com/19224038/27950837-0c43dc20-6303-11e7-95af-a1a15961d512.png)
The icons are here but hidden. (We see a small clickable part on the right)
I tested for an API 19 and by xml and programmatically. 

When I do both at the same time :
- First add fragment 
![capture d ecran de 2017-07-07 11-02-32](https://user-images.githubusercontent.com/19224038/27951082-f8c51aaa-6303-11e7-8a88-94a5be16ae92.png)
- After replace
![capture d ecran de 2017-07-07 11-02-41](https://user-images.githubusercontent.com/19224038/27951094-07790d04-6304-11e7-9868-d2cb6d4eb099.png)

Can you solve the problem ? Thx

**Comment by J-Jamet** [comment]
Otherwise good library. I will look at the source code if I have the time. ;)

**Comment by JoaquimLey** [comment]
First of all thanks for the kind words 👊

I'm not sure I follow what your problem here is, I can see the bug in the second image but you gotta give me a little more context so I can help you. How are you inflating the menu?

Like yourself, I don't have much spare time so I would appreciate if you could elaborate on your question so we can get to a solution faster. 🙃

**Comment by J-Jamet** [comment]
Of course, for the collaboration, I know what it is to make libraries. ;) I will try to be precise, you have access to the source code.

The menu is inflating programmatically in XML 
```<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@+id/faboptions_reminder"
        android:icon="@drawable/ic_add_alarm_white_24dp"
        android:title="@string/reminder_title" />
    <item
        android:id="@+id/faboptions_auto_message"
        android:icon="@drawable/ic_message_white_24dp"
        android:title="@string/auto_sms_title" />
</menu>
```
and in my layout FabOptions is in LinearLayout, below RecyclerView [Source code](https://github.com/Kunzisoft/RememBirthday/blob/master/app/src/main/res/layout/fragment_details_buddy.xml)
```
<com.joaquimley.faboptions.FabOptions
            android:id="@+id/fragment_details_buddy_fab_options"
            app:button_menu="@menu/menu_reminders"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|center" />
```

It's weird, because it works well when I change the fragment in my Activity with 2 panels in Landscape  ; line 158 [Source code](https://github.com/Kunzisoft/RememBirthday/blob/master/app/src/main/java/com/kunzisoft/remembirthday/activity/ListBuddiesFragment.java) , but not in my Activity with 1 panel in Portrait ; commented lines 110 -> [Source code](https://github.com/Kunzisoft/RememBirthday/blob/master/app/src/main/java/com/kunzisoft/remembirthday/activity/DetailsBuddyActivity.java)

I tried to initialize the menu without going through the layout with `.setButtonsMenu` but do the same thing.

Maybe it comes from the calculation of the width of the view for the animation or something like that.

**Comment by J-Jamet** [comment]
So I have completely change my code and I no longer use your library. :/
I think the bug comes from CoordinatorLayout and CollapsingToolbarLayout behind the fragment who contains FabOptions view but I'm not sure.
You can close the issue if you want, but I may add some functionality to your library later.
Have a nice day

**Comment by JoaquimLey** [comment]
Cool what alternative did you go with?

**Comment by J-Jamet** [comment]
I created a menu view that I animate with a https://github.com/ozodrukh/CircularReveal. But it's specific to my layout. :/

**Comment by JoaquimLey** [comment]
I know maybe it's too little too late, but you could've reset your buttons when the `Activity` is recreated, I'm thinking about doing another release and I'll probably expose #35  the `open()` and  `close()` methods, that might help to better handle the view.
