### ISSUE TITLE
Adding menu programmatically

### ISSUE THREAD

**Issue by MazenSenih** [JoaquimLey/faboptions#37]
Hi, great job in here man!
So I would like to customize the menu at run time by letting the user specify which actions and apps to launch, is this possible?

**Comment by JoaquimLey** [comment]
Hello thanks ;)

You can see in the [How to use](https://github.com/JoaquimLey/faboptions#how-to-use) section of the ReadMe, use `setButtonsMenu()`

**Comment by MazenSenih** [comment]
Hi thanks for your response,
Yeah i saw that, I was thinking about changing the menu dynamically by the user so the icon and the click action will get changed too, I guess I should assign the menu resource at programming and handle the user custom needs at runtime to modify the menu as fits.

**Comment by JoaquimLey** [comment]
No problem Mazen ;)

Yes I guess so, using a menu resource just makes everything simpler if you want such a custom implementation I would recommend the same implementation as you said, just handle your cases at runtime ;)
