### ISSUE TITLE
can it be show on home screen as a floating shortcut?

### ISSUE THREAD

**Issue by pourya0111** [JoaquimLey/faboptions#42]
hey there i saw this library and honestly its what i looking for for almost a year
but as i'm new in android studio 
i have a question 
can this fab be shown on home screen as a floating shortcut using service?

**Comment by JoaquimLey** [comment]
Hi @pourya0111 
I'm glad this library is useful for you, the implementation you are requesting I'm not 100% sure it'll work, but the library doesn't really how it's used :).
