### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by esparham** [JoaquimLey/faboptions#49]
Library is not compatible to appcompat 27+.

**Comment by JoaquimLey** [comment]
Yes, it is.

Can you please provide more context and or a stacktrace?  :) 

Thanks

**Comment by esparham** [comment]
Dear Ley,
As I checked, there is some issue regarding version 1.2.0 of your library.
In version 1.2.0, after adding fab in layout, nothing happens.
And library is not compatible to appcompat version 27+. I will send you log
cat.

Some scree shots are attached.

Thank you :-)

**Comment by JoaquimLey** [comment]
Hi there @esparham still haven't gotten any logs and or screenshots :)
