### ISSUE TITLE
i want to make the view display on the vertical direction.

### ISSUE THREAD

**Issue by greedbird** [JoaquimLey/faboptions#5]
How to set the vertical direction of the control display? Hoping to get your help.

**Comment by JoaquimLey** [comment]
@greedbird this is something I've been debating if I should set the direction or keep it as close to the concept as possible.
Of course having one component that does it all is better, but I would probably create another component.

**Comment by greedbird** [comment]
Thank you for your answers and look forward to your new component.

**Comment by mtaandaoio** [comment]
Hello, I must admit, this faboptions really has saved my ass. I have used it in 4 apps already and it works smoothly. If only the menu could open vertically, so it could be placed anywhere and not necessarily at the bottom. (Scenario: I have a listview of profiles, and another activity with profile details. I'm considering adding faboptions for contacting the profile user, i.e call, email, et al. Having the menu open vertically would be great for this.) 
Thanks.

**Comment by JoaquimLey** [comment]
Hi @mtaandaoio thanks for the kind words, I'm really happy to know this lib has helped you.

Regarding the feature per-se I'll try to code it asap, notice it's a pretty big feature since this has to work both on compile and runtime :)

**Comment by JoaquimLey** [comment]
I need to take a new approach to how the elements would respond, I will create a new issue and reference this one.
