### ISSUE TITLE
Backport to API 14+

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/faboptions#7]
The current implementation has a very demanding minSdkVersion 21 which severely limits usage.

## Context

Most of the limitations are in the Vector Drawable Animations

## Process

1. Set minSdk to 14 in `build.gradle`
2. Verify minSdk related  errors
3. Port/Limit functionalities for lower APIs

## Expected result

The library should be usable for API 14+

**Comment by Jawnnypoo** [comment]
Support library vector drawable compat does not support path animation, so this unfortunately will be a bit of work.

**Comment by JoaquimLey** [comment]
Yes you are right @Jawnnypoo the idea is not to have the same features as the >21 but to have a backport, some functionalities are lost due to lack of support of the framework. 👍

**Comment by liyinyin** [comment]
Hei, Could you publish the API 14+ version to Bintray? Now, I must download the source. Thank you very mush. @JoaquimLey

**Comment by JoaquimLey** [comment]
Hello @liyinyin I've actually had some corner cases with this PR, I'm just reviewing everything before publishing a new version.
Sorry I've been really busy and haven't been able to contribute as quickly as I wished.

**Comment by liyinyin** [comment]
@JoaquimLey Of course. You need to finish you job first. Thank you for your reply. Good luck.

**Comment by mtaandaoio** [comment]
Good luck, man. Been having trouble compiling on <21 devices. works okay on v5.1 up, although when you start an app the menus are open, and are over the keyboard when typing. Adding listeners should solve this, no?

**Comment by JoaquimLey** [comment]
Yes I know, @mtaandaoio Thanks for reporting 👍 that should be easy to fix.

**Comment by JoaquimLey** [comment]
https://android.jlelse.eu/animatedvectordrawablecompat-3d9568727c53#.yt10kdumwhttps://android.jlelse.eu/animatedvectordrawablecompat-3d9568727c53#.yt10kdumw
