### ISSUE TITLE
Coordinator behavior bug

### ISSUE THREAD

**Issue by alashow** [JoaquimLey/faboptions#8]
## Context
In sample app, after clicking snackbar test from menu, fab animates up, and gets back when SnackBar goes down automatically. But when user hides SnackBar manually, with swiping to right, fab button doesn't get back, it stays in wrong position.

## Process

1. Open Sample app
2. Click "Snackbar test" option from toolbar menu
3. Swipe right snackbar to hide

## Expected result
 
Fab button should animate down after closing snackbar.

### Thanks!

**Comment by JoaquimLey** [comment]
@alashow thanks for reporting, I've confirmed this bug, shouldn't be too hard to fix ;).
